### ISSUE TITLE
[Feature request] Support for Timeless skin

### ISSUE THREAD

**Issue by RogueScholar** [leon-do/solarized-chrome#4]
Great implementation of the Solarized palette to the Vector skin, but as someone who does a lot of editing on Wikipedia, Vector just doesn't cut it for me; I have to use the [Timeless skin](https://www.mediawiki.org/wiki/Skin:Timeless). Please ping me if support for it is ever added.

### Potential shortcut to adding support

Timeless has had a [semi-official dark mode CSS](https://github.com/Austemagne/DarkTimeless) offered for interested wiki admins to install on a site-wide basis. It's somewhat less effective as a user mod (I'm speaking from experience), but probably not for someone with a tight grasp of CSS mechanics. If I had the talent and free time to pursue this, that's probably what I'd try first. I'm more than happy to alpha test if you get anything even halfway down the path to completion.

**Comment by leon-do** [comment]
sorry for the multiyear delay. the chrome extension updated. Feel free to look at it/open new issue!
